  version: '3.8'

  services:
    postgres:
      image: postgres
      container_name: my-compose-postgres
      environment:
        POSTGRES_PASSWORD: pass
      ports:
        - "5432:5432"

    adminer:
      image: adminer
      container_name: my-compose-adminer
      ports:
        - "8080:8080"
      depends_on:
        - postgres